### ISSUE TITLE
Exception in thread Thread-2

### ISSUE THREAD

**Issue by sansplomb** [jackjennings/Mechanic#11]
Trying to install Curve-Equalizer extension; the progress bar freezes:

output:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "threading.pyc", line 763, in run
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/progress.py", line 19, in wrapped
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/progress.py", line 35, in wrapped
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/progress.py", line 35, in wrapped
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/tabs/install.py", line 41, in install
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 25, in install_remote
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/event.py", line 24, in wrapped
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 44, in install
  File "lib/scripting/extensionBundle.pyc", line 503, in install
  File "lib/scripting/extensionBundle.pyc", line 522, in _install
  File "lib/scripting/extensionBundle.pyc", line 297, in validate
  File "lib/scripting/extensionBundle.pyc", line 327, in validateInfo
  File "lib/scripting/extensionBundle.pyc", line 112, in infoDictionaryPath
  File "posixpath.pyc", line 77, in join
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by sansplomb** [comment]
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "threading.pyc", line 763, in run
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/tabs/updates.py", line 62, in update_list
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/lists/update.py", line 40, in refresh
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 27, in all
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 57, in _get_cached
TypeError: list indices must be integers, not unicode

**Comment by jackjennings** [comment]
Try installing Mechanic from the installation list and restarting. I think that I pushed an update that fixed this while I was at Robothon. Might still be broken, but I'm about to board a flight for a few hours and I can check when I get off.

**Comment by sansplomb** [comment]
Seems to be fixed. Thanks
