### ISSUE TITLE
bad zip file

### ISSUE THREAD

**Issue by typemytype** [jackjennings/Mechanic#15]
got a weird traceback when trying to install 'Cross Overlap'

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "threading.pyc", line 763, in run
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/progress.py", line 19, in wrapped
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/progress.py", line 35, in wrapped
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/progress.py", line 35, in wrapped
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/tabs/install.py", line 41, in install
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 24, in install_remote
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/event.py", line 24, in wrapped
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/github/repository.py", line 23, in download
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/github/downloader.py", line 41, in extract
  File "zipfile.pyc", line 766, in __init__
  File "zipfile.pyc", line 807, in _RealGetContents
BadZipfile: File is not a zip file
```

**Comment by jackjennings** [comment]
Updated the record on the server which has a repository name that didn't match, and I added a new validation to the server software to catch that error in the future.
