### ISSUE TITLE
Instability issue

### ISSUE THREAD

**Issue by bahman3d** [jackjennings/Mechanic#16]
It's been a while that I realized when I have the mechanic installed, Robofont crashes sometimes. I uninstalled it couple of times and checked back in a while to see if the issue has resolved but no dice. I also wanted to check updates on the extension and Robofont goes to a halt state. I guess the issue has started in the past two months. I was wondering if anyone else has same problem?

**Comment by jackjennings** [comment]
Which version of RoboFont are you using? Do you have the most recent version of Mechanic installed? Roughly how many extensions do you have installed?

This is a known issue, but not one that I know the solution to. The easiest workaround right now to to uncheck the "Check for updates on startup" setting in the Mechanic controls. The caveat to this is that you will need to manually check for new updates.

**Comment by bahman3d** [comment]
Sorry I forgot to add the output so I updated my question. I'm using Version 1.6 (built 1410152315). Ok I try to disable "Check for updates on startup". Let's see how it goes.

Thanks!

**Comment by jackjennings** [comment]
Strange, I haven't seen this issue previously. Let me see if I can reproduce it with the same build.

**Comment by jackjennings** [comment]
I think that this should be resolved in the new version I just released. Can you give this a try and see if the same issue is occurring?

https://github.com/jackjennings/Mechanic/archive/1.3.0.zip

**Comment by typoman** [comment]
Thanks, I experienced a crash with that option on after installing the new version even it said it's version 1.2.0 in the installation dialogue. Not sure if it was related to Mechanic but this happens rarely. Without that option it seems fine. I have to work with it for a day or two to make sure if turning the option off helps.  I guess when the extension couldn't connect to server it halts or causes recursion or something that leads to crash. Crash happens suddenly under a second.

**Comment by typoman** [comment]
BTW I got this in the python output:

Traceback (most recent call last):
  File "_startup.py", line 19, in <module>
  File "/Users/bahmaneslami/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/event_caller.py", line 10, in __init__
NameError: global name 'Bus' is not defined

**Comment by jackjennings** [comment]
Do you get the same output when you restart RoboFont?

**Comment by typoman** [comment]
Yes. I just tested.

**Comment by jackjennings** [comment]
I just pushed a fix for this as version 1.3.1. Sorry about that, I'm not sure why this worked on my end… it probably shouldn't have.

**Comment by typoman** [comment]
It's okay :). I just installed and see what happens. Thanks!

**Comment by typoman** [comment]
Ok after a day I can tell you definitely turning the "Check for updates on startup" makes a difference and prevents Robofont from crashing. Having the option on causes crash about every 30 minutes or so, not quite sure about the intervals.

**Comment by jackjennings** [comment]
Can you please try installing version 1.3.2? https://github.com/jackjennings/Mechanic/archive/1.3.2.zip

This version should report the correct version number on installation and solve the crashing issue even when "Check for updates on startup" is selected.

**Comment by typoman** [comment]
Sorry for delay but the version 1.3.2 also crashes with that option on. I wish I could understand how it's working and help you to fix the error.
