### ISSUE TITLE
expatError

### ISSUE THREAD

**Issue by typemytype** [jackjennings/Mechanic#18]
```
******************************
Traceback (most recent call last):
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/threaded.py", line 62, in run_
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/tabs/updates.py", line 64, in update_list
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/lists/update.py", line 40, in refresh
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 25, in all
  File "/Users/frederik/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 39, in _fetch_updates
ExpatError: not well-formed (invalid token): line 34, column 0

******************************
```

**Comment by typemytype** [comment]
There was an extension that has a malformed info.plist file (an extension Im working on)

This should not happen but it could be possible that one of the installed extension is not valid...
maybe Mechanic should skip those?

An `ExentsionBundle` has a `validate()` callback that you can use

**Comment by jackjennings** [comment]
I had a hunch that this was the issue, and I was looking into how to `except` from this. Python errors are kind of frustrating to work on when the error originates from a library, but I think that I have a solution that I can release later today.

Which extension had the plist in question?

**Comment by typemytype** [comment]
solved here

https://github.com/typemytype/RoboFontExtensions/commit/8ebb8da3bcb9e17da62c179bfa0d4b8bc4808241

dont understand where those > went...

**Comment by jackjennings** [comment]
Hey @typemytype, I added an exception that fixes this case, and a warning (which will be logged when I get that running again).

**Comment by typemytype** [comment]
thanks
