### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by flopflip21** [jackjennings/Mechanic#6]
Get the following error on startup

```Traceback (most recent call last):
  File "_startup.py", line 20, in checkForUpdates
  File "/Users/flopflip/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/views.py", line 78, in __init__
  File "/Users/flopflip/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/models.py", line 162, in all
  File "/Users/flopflip/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/models.py", line 173, in _fetchUpdates
  File "/Users/flopflip/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/models.py", line 18, in __init__
  File "/Users/flopflip/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/models.py", line 29, in configure
  File "/Users/flopflip/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/models.py", line 58, in __init__
ValueError: too many values to unpack
```

**Comment by jackjennings** [comment]
It looks like it's still trying to run the old version of Mechanic (`models.py` no longer exists in 1.0.0). Can you please restart RoboFont and verify that solves the issue?

**Comment by jackjennings** [comment]
Ahh, perhaps you actually *were* running the old version of mechanic. There was some extensions that were not configured correctly, and Mechanic version 0.6.0 and lower would have thrown an error when trying to read it.

Try upgrading to the version 1.0 that I just released and see if that solves the issue for you.

**Comment by jackjennings** [comment]
If you have the extension "Ground Control" installed, you should also re-install it from the "Install" tab to make sure you have the most recent version.

**Comment by flopflip21** [comment]
Issue solved! Just had to reinstall it
