### ISSUE TITLE
Traceback (AttributeError: 'NoneType' object has no attribute 'get')

### ISSUE THREAD

**Issue by t42-ink** [jackjennings/Mechanic#7]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyc", line 810, in __bootstrap_inner
  File "threading.pyc", line 763, in run
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/windows/notification.py", line 20, in __init__
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/windows/notification.py", line 74, in get_updates
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 25, in all
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 39, in _fetch_updates
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 66, in should_update
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 58, in is_current_version
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/lazy_property.py", line 15, in __get__
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/github/repository.py", line 35, in version
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/lazy_property.py", line 15, in __get__
  File "/Users/jeremiehornus/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/github/repository.py", line 46, in extension_path
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by jackjennings** [comment]
Can you try installing Mechanic again directly from the Install tab, and confirm that the traceback doesn't occur (after restarting RF)? If you get a warning instead, can you also please share the output?

**Comment by t42-ink** [comment]
Just did that. It works fine now. Thanks very much :)

**Comment by jackjennings** [comment]
Did you get a warning instead of the traceback? I'm trying to pinpoint if there are any extensions that might be configured incorrectly, which would cause an error at this point in the program.

**Comment by t42-ink** [comment]
Yes I did get some warnings about some extensions (word-o-mat, curve equalizer, etc.) but did not copy them in time.
Now I cannot reproduce them.

**Comment by jackjennings** [comment]
OK, that means it's OK. :)
I'm going to close this issue, but reopen if you see any additional problematic output.

**Comment by t42-ink** [comment]
2015-02-17 19:20:42,479 - Mechanic - WARNING - Couldn't get information about Arrange Windows.roboFontExt from typemytype/RoboFontExtensions
2015-02-17 19:21:08,481 - Mechanic - WARNING - Couldn't get information about AdjustMetrics.roboFontExt from FontBureau/fbOpenTools
2015-02-17 19:21:12,473 - Mechanic - WARNING - Couldn't get information about AddOverlap.roboFontExt from asaumierdemers/AddOverlap
2015-02-17 19:21:13,985 - Mechanic - WARNING - Couldn't get information about word-o-mat.roboFontExt from ninastoessinger/word-o-mat
2015-02-17 19:21:16,809 - Mechanic - WARNING - (Probably) Couldn't fetch the GitHub file tree for gferreira/hTools2
2015-02-17 19:21:19,147 - Mechanic - WARNING - (Probably) Couldn't fetch the GitHub file tree for gferreira/hTools2
2015-02-17 19:21:36,241 - Mechanic - WARNING - (Probably) Couldn't fetch the GitHub file tree for gferreira/hTools2
