### ISSUE TITLE
Error while trying to register an extension

### ISSUE THREAD

**Issue by jenskutilek** [jackjennings/Mechanic#8]
As soon as I start Mechanic with the "Register" tab, I get this in the output window:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyc", line 808, in __bootstrap_inner
  File "threading.pyc", line 761, in run
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/windows/notification.py", line 20, in __init__
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/ui/windows/notification.py", line 74, in get_updates
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 25, in all
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/update.py", line 39, in _fetch_updates
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 66, in should_update
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 58, in is_current_version
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/extension.py", line 91, in version
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/mechanic/version.py", line 20, in __init__
  File "/Users/jens/Library/Application Support/RoboFont/plugins/Mechanic.roboFontExt/lib/site-packages/semversion.py", line 92, in __init__
VersionError: invalid version '2.0b2'```

**Comment by jenskutilek** [comment]
Actually, I don't need to do anything, the crash occurs when Mechanic is only installed, no interaction required.

**Comment by jackjennings** [comment]
Do you know which extension has the version `2.0b2`?

**Comment by jenskutilek** [comment]
Ah, okay, it's an extension that is not in a public repository. It had a repository key for mechanic anyway. When I remove it, everything's fine.

**Comment by jackjennings** [comment]
I'm going to keep this open, so that I can do something in regards to capturing this error before it raises.

If you do want to use a `beta` flag on the version, you should be able to do so as long as it conforms to the semantic versioning spec: http://semver.org

**Comment by jackjennings** [comment]
E.g. `1.0.0-beta`. You might have to also include the patch level version as well?

**Comment by jenskutilek** [comment]
Thanks!

**Comment by jackjennings** [comment]
I've added a try/catch and a warning describing acceptable version numbers. Thanks or submitting the bug!
